### ISSUE TITLE
Use Statamic CP_ROUTE environment variable

### ISSUE THREAD

**Issue by bymazzeo** [appswithlove/statamic-one-click-content-translation#11]
Hello, 

we just bought your statamic addon and while evaluating it we found this issue with the following situation.

We use different routes for various environments (development, staging, production,...) by setting the variable CP_ROUTE on the corresponding .env file for security reasons. 

We noticed that the axios request used to translate has the default statamic route 'cp' hardcoded.

`const URL_TRANSLATE = '/cp/one-click-content-translation';`

file: /resources/js/api.js
````
const URL_TRANSLATE = '/cp/one-click-content-translation';

export function translateMeRequest(payload) {
  return Statamic.$axios
    .post(URL_TRANSLATE, payload)
    .then((response) => {
      Statamic.$toast.success(__('Done'));
      return response;
    })
    .catch((error) => {
      Statamic.$toast.error(error?.response?.data.message || error.message);
      return { data: payload };
    });
}
`````

Could it be possible to use the .ENV variable CP_ROUTE or add another means to modify this?

Many thanks!

**Comment by OleksiiBrylin** [comment]
Hello. 

It makes sense. 
You can wire a MR, or wait few days.

**Comment by OleksiiBrylin** [comment]
@bymazzeo 
updated in 4.18.2

**Comment by bymazzeo** [comment]
Great, many thanks!
