### ISSUE TITLE
Statamic report's update required

### ISSUE THREAD

**Issue by jbrhel** [appswithlove/statamic-one-click-content-translation#12]
Hello,

I have the latest version of this addon installed, but Statamic still reports that this addon needs to be updated. It's not critical, but it's quite confusing. Could you please take a look at it?

Thank you!

<img width="215" alt="statamic_update" src="https://github.com/appswithlove/statamic-one-click-content-translation/assets/1133430/77baadb2-c6fa-4e8e-85b5-ff713878dadc">

**Comment by OleksiiBrylin** [comment]
@jbrhel fixed
