### ISSUE TITLE
Bard field translations doesn't work if set Character Limit

### ISSUE THREAD

**Issue by OleksiiBrylin** [appswithlove/statamic-one-click-content-translation#15]
Please check this quick recording: https://drive.google.com/file/d/1XGdupAucxoyOr197RI_0jBtw6xybjdTx/view?usp=drivesdk . You will notice that around seconds 0:06-0:10, in the second field that I try to translate, nothing happens. But the others work fine.

Payload
```
{"selectedLang":"es","defaultLang":"en","texts":[{"index":0,"html":"Download your YouTube Shorts in any file format or quality. Paste your Shorts URL, select format and quality, then download it in a matter of seconds!"}]}
```

Response
```
{
    "selectedLang": "es",
    "defaultLang": "en",
    "texts": [
        {
            "index": 0,
            "html": "Descarga tus cortos de YouTube en cualquier formato o calidad de archivo. Pega la URL de tus Shorts, selecciona el formato y la calidad, \u00a1y luego desc\u00e1rgalo en cuesti\u00f3n de segundos!"
        }
    ]
}
```

**Comment by OleksiiBrylin** [comment]
I realized that it is not a bug. 
the behavior is: If you write long text and after translation the text will be bigger than allowed limit the field will ignore input. 

Does it make sense for you? @diogovitzo

**Comment by diogovitzo** [comment]
Ah! Yes! You're totally right...

No idea why I set a max character limit on that field 😑. It's all good now. Thanks for taking a further look into this and sorry for wasting your time. You may close the issue.
