### ISSUE TITLE
Supporting markdown fields?

### ISSUE THREAD

**Issue by geertjanknapen1** [appswithlove/statamic-one-click-content-translation#16]
Is there any plans to also support markdown fields?

We use sets within Bard fields, but these sets cannot contain another Bard field, so we fix this using a Markdown field. But those do not get the `one-click-translation` button, and are not translatable with a click.

**Comment by OleksiiBrylin** [comment]
Hi @geertjanknapen1 
Yes, we are planing to connect Markdown type in 1-2 weeks.

**Comment by OleksiiBrylin** [comment]
@geertjanknapen1 support of Markdown field implemented
