### ISSUE TITLE
Button always available, also in origin.

### ISSUE THREAD

**Issue by geertjanknapen1** [appswithlove/statamic-one-click-content-translation#17]
This is more of a question, but I recently updated to a later version (4.60.0), and the translate button is now always available. Even when the current site is the origin site.

This did not happen before and I am not sure if it is intended behavior.

**Comment by OleksiiBrylin** [comment]
Yes, it was changed. Now the button is available for default language too.
 
For example: if your native language is english but the site is on french. You can write sentence on english and click the button. It will translate the text to the french language. 

* note: you have to set up `ignore_source_lang=true` in config or use `google` as a translation service

**Comment by geertjanknapen1** [comment]
@OleksiiBrylin Hi again, i added `ignore_source_lang=true` in the config. But this does not disable the button in origin.
