### ISSUE TITLE
Fieldtype [one_click_content_translation_inputs] not found

### ISSUE THREAD

**Issue by bygstudio** [appswithlove/statamic-one-click-content-translation#3]
After successful install "Fieldtype [one_click_content_translation_inputs] not found" error appear on Collection, or Blueprint pages
`/cp/collections/articles/blueprints/article/edit`
`/cp/collections/articles`
PHP ver: 8.1.6
Laravel: 9.31.0
Statamic: 3.4.3

**Comment by imakeitworknet** [comment]
Same issue in Statamic 3.3.65, PHP 8.1.

**Comment by SG-fabian** [comment]
Can confirm in Statamic 3.4.4.

`please make:fieldtype OneClickContentTranslationInputs` fixes the error (of course it does) but then the fields are broken (of course they are).

**Comment by imakeitworknet** [comment]
> `please make:fieldtype OneClickContentTranslationInputs` fixes the error (of course it does) but then the fields are broken (of course they are).

that one seems enough to get it working on Statamic 3.3.65 :) Thanks! For Statamic v3.4 it will probably be Bard compatibility issues.
