### ISSUE TITLE
Question: Support for glossary?

### ISSUE THREAD

**Issue by geertjanknapen1** [appswithlove/statamic-one-click-content-translation#37]
It seems that this plugin does not take [glossaries](https://developers.deepl.com/docs/api-reference/glossaries#retrieve-glossary-details) into account.

Are there plans to allow for the use of glossaries with the plugin?

**Comment by OleksiiBrylin** [comment]
Hi @geertjanknapen1 

I added possibility to set up Glossary in Deepl config. (v4.63.0)
Please check if it matches your request.

The option array was added to config/statamic-one-click-content-translation.php, as `deepl_options` option.

More info: https://github.com/DeepLcom/deepl-php/blob/main/src/TranslateTextOptions.php
