### ISSUE TITLE
Does not translate Bard fields

### ISSUE THREAD

**Issue by imakeitworknet** [appswithlove/statamic-one-click-content-translation#4]
Using master branch (2023-02-17) after update.
Statamic 3.3.65, PHP 8.1.

Translator works with any field except Bard.

Translation icon shows up, seems to be active, but after clicking it nothing happens. Tried plain Bard field without Sets, tried with Sets - no difference in behavior. With heading, only plain paragraphs. The same result.

Any tips?

**Comment by OleksiiBrylin** [comment]
Please check version. It should be v0.9.2
Re install assets 
php artisan vendor:publish --tag="statamic-one-click-content-translation"

**Comment by imakeitworknet** [comment]
Yes, now it's working. Thanks!
