### ISSUE TITLE
Feature Request: Ability to translate an entire entry on save

### ISSUE THREAD

**Issue by mgtcampbell** [appswithlove/statamic-one-click-content-translation#44]
Hi there,

Wondering if there's any plans to allow a whole page to be translated at once, instead of field by field.

Further to that would be the ability to set this to automatically happen for any pages in other languages on Save.

Example:

- Website has 4 languages - English, Spanish, French, German
- A given page - e.g. "Service Offering 1" - is published on the English and Spanish sites, not on the other two
- A user makes a change to content on the English site and Saves the update
- This is then when the translator would kick in and make any required updates to the Spanish version since it is also already published
- It would not make any edits or try and publish a version for the French or German sites since this page does not currently exist on those

We have a client with a multisite who is saying it would still be too much manual work to click on the translate button on every language version every time they make a small udpate.

I understand this is far beyond the current scope so just interested to know if it's something that's being considered.

Cheers
Mark

**Comment by OleksiiBrylin** [comment]
Having it done automatically seems to be a bigger task to handle different cases and problems. 
We are not planning to make this function in next 3-6 months

**Comment by mgtcampbell** [comment]
Thanks @OleksiiBrylin - appreciate this is a much tougher task.

In the meantime I have done some work on an attempt to do this myself and it has presented some unique challenges for sure.

**Comment by OleksiiBrylin** [comment]
one of the possible solution can be - to find, translate and replace text strings directly in .md files by regular expression. 
It will not cover all cases like stored in DB data, or some uniq cases of some projects. But it can perfectlly make simple entry translations. 

```
        $regexp = '/(title|text|caption|date|content): ([\"]([\s\S\n]+?)[\"]|[\']([\s\S\n]+?)[\']|([\s\S]+?)\n)/';
        preg_match_all($regexp, file_get_contents($filePath), $matches, PREG_SET_ORDER, 0);

        foreach ($matches as $key => $text) {
```

**Comment by mgtcampbell** [comment]
Thank you, that's super helpful - not an approach I had considered.

To start I was pulling the Statamic Entry model and then getting the json for the content via the `$entry->data();` method... but the issue there is that it's hard to tell within the json data which parts are _actual_ text entries vs just other text within the json data as it doesn't make any mention of field type.

I also tried pulling `$entry->blueprint()->fields()->all();` to cross reference the field types, however since I am importing a number of field types this only returns the name of the import, not the field types within that input.

I'll look into your suggestion of pulling from the markdown files directly instead.
