### ISSUE TITLE
Add-on's translate button does not appear in bard Sets

### ISSUE THREAD

**Issue by Sennik** [appswithlove/statamic-one-click-content-translation#6]
The translate button does not appear in the fields from the Sets within a bard field type, correct?

Or is it something I did wrong?

**Comment by OleksiiBrylin** [comment]
It should appear. Please add Statamic, php version information and a screenshot of your sets.

**Comment by Sennik** [comment]
![afbeelding](https://user-images.githubusercontent.com/5636394/232587911-8e66c972-a149-44e2-ab61-da872d87174e.png)

What do you want to see, the bard field wit the configured sets (too long for a screenshot) or the page where it is used? Do you want one set opened?

**Comment by OleksiiBrylin** [comment]
Thank you for the screenshot. 
It is more more clear now.

Have you tried to open another language? 

Note: The Add-on's translate button shouldn't appear for a default language.
